language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: trusty

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - pear config-set preferred_state snapshot && yes "" | pecl install mcrypt ;
  - |
    bash -c "
    mysql -u root -e \"CREATE DATABASE basercms CHARACTER SET utf8;\";
    mysql -u root -e \"CREATE DATABASE test_basercms CHARACTER SET utf8;\";
    mysql -u root -e \"SET GLOBAL time_zone = 'Asia/Tokyo'\";
    mysql -u root -e \"GRANT ALL PRIVILEGES ON basercms.* TO basercms@localhost IDENTIFIED BY 'basercms';\";
    mysql -u root -e \"GRANT ALL PRIVILEGES ON test_basercms.* TO basercms@localhost IDENTIFIED BY 'basercms';\";
    ";
  - mysql -ubasercms -pbasercms basercms < __assets/basercms.sql;
  - cp config/app_local.example.php config/app_local.php
  - cp config/.env.example config/.env
  - sed -i -e "s/'host' => 'bc5-db'/'host' => 'localhost'/g" config/app_local.php;
  - sed -i -e "s/'username' => 'root'/'username' => 'basercms'/g" config/app_local.php;
  - sed -i -e "s/'password' => 'root'/'password' => 'basercms'/g" config/app_local.php;
  - composer self-update;
  - composer install;
script:
  - vendor/bin/phpunit

notifications:
  email: false
